### ISSUE TITLE
Incompatibility with shrinkwrap when using npm 2

### ISSUE THREAD

**Issue by sdepold** [nodesecurity/gulp-nsp#24]
Hey there,

are there any plans to support npm 2? The project is currently not usable with the latest TLS version of node without major bumping npm. 

I saw this https://github.com/nodesecurity/gulp-nsp/issues/20 but upgrading to npm3 is not really an option for everyone.

Greetings,
Sascha.

**Comment by nlf** [comment]
updating npm on the LTS build of node should be perfectly safe. we understand that it's annoying to have things not work correctly, though. we'll continue to work towards finding a better fix. thanks for letting us know.

**Comment by joeycozza** [comment]
I believe that the latest release of this module has been shrinkwrapped with npm v2, so this issue shouldn't exist anymore...but that DOES mean that https://github.com/nodesecurity/gulp-nsp/issues/26 (verifying shrinkwrap with npm 3 doesn't work now) exists.

I personally have never used shrinkwrap, so what is the protocol for npm 2 vs npm 3 and shrinkwrapping npm modules?

**Comment by SrinivasanTarget** [comment]
Its not working with either Npm2 and npm3

**Comment by SrinivasanTarget** [comment]
It works only when it is pointed to package.json

**Comment by joeycozza** [comment]
I'll have to look into this later then, but I still don't know what course of action we should take concerning shrinkwrapping gulp-nsp with npm2 vs npm3.

**Comment by SrinivasanTarget** [comment]
yes please @joeycozza But i dont see this working (shrinkwrap) for both npm versions. Would be great if we get a fix for it asap.

**Comment by sdepold** [comment]
Honestly: why aren't you just removing the shrinkwrap file and - if even needed - pinpointing the versions in the package.json

I can sort of understand shrinkwraps for applications, in which you want to be explicit about the things, that are going to be installed. But for a helper lib  that is "only" a bit in a building tool chain which most likely never even comes close to a non-dev machine it seems a bit off.

**Comment by joeycozza** [comment]
I wouldn't use the shrinkwrap personally, but I believe it is nodesecurity's policy. From what I remember they always use shrinkwrap and shrinkydink before they'll accept a pull request. @nlf Input?

**Comment by SrinivasanTarget** [comment]
It works only if we specify both shrinkwrap and package together.

**Comment by nlf** [comment]
we use shrinkwrap in the nsp projects because it helps make sure that we're shipping consistent code for everyone.

we likely can change things to just specify exact versions in the package.json, and that's something we've had a bit of discussion around. the down side is that doesn't let us guarantee specific versions of subdependencies. i think given the number of people having issues with our shrinkwrap files we may end up moving in that direction anyway, but i'll have to talk to @evilpacket about it.

**Comment by wraithgar** [comment]
The latest version of this, `v2.4.0` should work with npm 2.  We are now building our shrinkwrap files in npm 2, which work just fine under npm 3. So both should now be supported.
