### ISSUE TITLE
Receive a file stream instead of a string.

### ISSUE THREAD

**Issue by lucasfcosta** [nodesecurity/gulp-nsp#25]
Hi guys, thanks everyone for your hard work, I really appreciate it, but while taking a look at your source code I've thought about the following:

Personally I think it would be much more correct if we receive a stream of files instead of just calling the `nsp` function and returning a callback. The current version of `gulp-nsp` does not follow gulp's paradigm at all, it's just a common module that exports a single function.

That isn't exactly harmful to the module's overall functionality, but it simply doesn't comply with gulp standards, so I'm here to make a refactor proposal to you guys.
# How it would work

Using it would require piping a string through it, like the other gulp plugins do. It would be something like:

``` js
nsp = require('gulp-nsp');

gulp.task('nsp', () => {
    return gulp.src('myfolder/**/package.json')
        .pipe(nsp({
          stopOnError: true,
          proxy: 'example',
          output: 'default'
        }));

});
```

**Why this is good:**
1. It allows users to pipe more than one `package.json` file into our plugin
2. It would allow the user to configure whether his entire build/task list should fail or not (exit with exit code 1) according to NSP results (Personally, I think this would be awesome!)
3. its syntax is similar to other plugins', making its use more intuitive
4. It works like every other gulp-plugin
5. It follows gulp's paradigm
6. It enables us to emit events and therefore we will be able to handle conditions like `stopOnError` in a better way. Doing this will also allow us to handle multiple file results and have more exhibition options.
7. It enables the user to pipe the output of this into another plugin
8. We won't need accept a callback anymore
9. It's clearer and more elegant in general

I will do more studies on this later if you guys find this change suitable for your module. I also plan on doing some fallbacks including deprecation warnings to prevent breaking everyone using the current version.

**I will also write some tests just to make sure everything works fine, including retrocompatibility.**

I think that's it, I can start the work as soon as you guys confirm this change can be made.
Thanks everyone!

**Comment by nlf** [comment]
hey, sorry this took so long for me to get back to you on. i think your points about this following gulp's paradigms are extremely valid and this makes a lot of sense. if you're willing to submit a pull request changing the plugin to work in this way, i'd be happy to merge it. if not it'll be a little while before one of us has time to address this ourselves.

**Comment by lucasfcosta** [comment]
Hi @nlf, no problem!
I'll work on this and submit a PR as soon as it's done.
Thanks for letting me help!

**Comment by phated** [comment]
Just found this module and I actually disagree with making this a stream.  The callback pattern is perfectly valid for gulpfriendly (ref: https://twitter.com/BlaineBublitz/status/728624347716329477) and this module doesn't really seem to warrant the stream interface.

**Comment by phated** [comment]
Sidenote to the above, I don't think `stopOnError` is a good option and instead, you should recommend the end user handles the error explicitly in their gulpfile.  Just my 2 cents.

**Comment by nlf** [comment]
i'm going to close this since it would require a pretty significant refactor of all the things and it works well as it is
