### ISSUE TITLE
Gulp nsp always throws error when set to verify shrinkwrap

### ISSUE THREAD

**Issue by SrinivasanTarget** [nodesecurity/gulp-nsp#26]
O/P:
gulp nsp
[20:24:46] Using gulpfile ~/AppiumRepo/appium/gulpfile.js
[20:24:46] Starting 'nsp'...
[20:24:46] 'nsp' errored after 6.07 ms
[20:24:46] Error in plugin 'gulp-nsp'
Message:
    (+) Error: package.json is required

Gulp File:
var gulp = require('gulp'),
    gulpNSP = require('gulp-nsp');

gulp.task('nsp', function (cb) {
  gulpNSP({shrinkwrap: __dirname + '/npm-shrinkwrap.json',stopOnError: true,output: 'summary'}, cb);
});

npm-shrinkwrap.json is available in exact path.

Help me in resolving this issue.

**Comment by SrinivasanTarget** [comment]
@evilpacket @joeycozza Can you help in resolving this error?

Additional inputs:
gulp --v
CLI version 3.9.1
Local version 3.9.1

npm -v
3.7.3

**Comment by SrinivasanTarget** [comment]
Here https://github.com/nodesecurity/gulp-nsp/blob/master/index.js#L37 we are checking based on package but i need to validate the nsp based on shrinkwrap.I think that condition is missing.Correct me if i'm wrong. @evilpacket @joeycozza

**Comment by joeycozza** [comment]
I believe that the most recent version of gulp-nsp was shrinkwrapped with npm 2, so when you shrinkwrap your app with npm 3, there are now issues. (similar, but reversed to the problem in https://github.com/nodesecurity/gulp-nsp/issues/24).

I have no idea what the protocol concerning this should be.  

Any advice/input @nlf ?

**Comment by pdehaan** [comment]
I think the easiest solution would be to specify the package.json as well:

``` js
gulp.task('nsp', function (cb) {
  gulpNSP({
    shrinkwrap: path.join(__dirname, 'npm-shrinkwrap.json'),
    package: path.join(__dirname, 'package.json'),
    stopOnError: true,
    output: 'summary'
  }, cb);
});
```

IIRC, the **gulp-nsp** module will still verify against the npm-shrinkwrap file, but was using the package.json file for some values.

I tested on the https://github.com/appium/appium repo and specifying `shrinkwrap` and `package` properties found 17 issues, whereas just specifying the `package` property only found 8.

**Comment by SrinivasanTarget** [comment]
@pdehaan I was trying to fix it in appium. please see this https://github.com/appium/appium/pull/6167

**Comment by SrinivasanTarget** [comment]
It works fine in above way @pdehaan Thanks!

**Comment by nlf** [comment]
@pdehaan is right, when running a check against a shrinkwrap you must also pass the package.json.

it sounds like after making that change things started working for you, so i'm going to go ahead and close this issue but please do reopen it if you're still having a problem.

**Comment by SrinivasanTarget** [comment]
Thanks @pdehaan @nlf @joeycozza

**Comment by pdehaan** [comment]
> @nlf: when running a check against a shrinkwrap you must also pass the package.json.

Why is that? It sounds a lot like https://github.com/nodesecurity/nsp/issues/50, where you said:

> "package shouldn't be required any more. it's possible we'll require it in the future, but for now we weren't actually using it for anything when the shrinkwrap was supplied, so we lifted it."

**Comment by nlf** [comment]
that behavior has changed. we're actually using the package.json when you pass in a shrinkwrap file now, so we do require both. we'll have to document how the checks are done exactly.
