### ISSUE TITLE
Naming convension

### ISSUE THREAD

**Issue by Zolmeister** [nodesecurity/gulp-nsp#3]
Gulp modules are prefixed, not suffixed
e.g.: `gulp-nsp`

In addition, this doesn't seem to have any gulp-specific code, so it may end up on the blacklist: https://github.com/gulpjs/plugins/blob/master/src/blackList.json

**Comment by diasdavid** [comment]
@Zolmeister I asked @joeycozza to name the module nsp-gulp because we have been using the 'nsp-' namespace for all nsp related tooling, however, I didn't know that it would break the gulp convection. 

@joeycozza feel free to decide in which way you prefer the module to be called :)

**Comment by joeycozza** [comment]
@diasdavid it would probably be good to follow gulp convention. I don't have rights to change the name of the repo anymore, so if you wanted to do that for me, that would be great.

When we do change the name, do I just unpublish the old nsp-gulp from npm, and publish gulp-nsp?  Or is there a way to change package names on npm?

**Comment by diasdavid** [comment]
I believe you will have to unpublish and republish. name changed :)

**Comment by joeycozza** [comment]
OK. I am away from my computer for the next few hours, but will take care of that ASAP.

**Comment by joeycozza** [comment]
Name has been switched to gulp-nsp, and the old nsp-gulp has been unpublished from npm.  Also, a contributor added some gulp specific code to log with gulp-util without breaking the gulp process, so I am going to close this issue.
