### ISSUE TITLE
shrinkwrap made with npm v2 adds lots of problems on Windows

### ISSUE THREAD

**Issue by vsenko** [nodesecurity/gulp-nsp#31]
Windows systems have limitations on the length of the path. According to the directory structure shrinkwrap file that is included with gulp-nsp is generated using npm v2 and it creates really deep directory tree.
We are using gulp-nsp for CI and Windows command `rd` fails to delete gulp-nsp folder after running tests.

**Comment by nlf** [comment]
shrinkwrap's gone
