### ISSUE TITLE
Cannot use thirdparty formatter

### ISSUE THREAD

**Issue by pdehaan** [nodesecurity/gulp-nsp#32]
Ref: https://github.com/nodesecurity/grunt-nsp/issues/19

Looks like we'll have the same issue [here](https://github.com/nodesecurity/gulp-nsp/blob/a1d1a130821fcd9fed4e0632d8159d0d27eea7ce/index.js#L25-L32) as in **grunt-nsp**. After merging https://github.com/nodesecurity/nsp/pull/122 we should tweak this repo and make sure it works with the custom **nsp-formatter-checkstyle** formatter.

**Comment by nlf** [comment]
nsp@2.6.0 is published with the exported method, just need to update this module to use it

**Comment by nlf** [comment]
you can do this now
