### ISSUE TITLE
gulp-nsp installs an outdated version of nsp, relying on vulnerable packages

### ISSUE THREAD

**Issue by skcc75** [nodesecurity/gulp-nsp#39]
The current version of nsp is 2.6.2, but gulp-nsp installs 2.3.0 which is outdated and relies on vulnerable packages:
```
+-- gulp-nsp@2.4.2
| `-- nsp@2.3.0
|   `-- nodesecurity-npm-utils@4.0.1
|     `-- silent-npm-registry-client@2.0.0
|       `-- npm-registry-client@7.1.0
|         `-- request@2.69.0
|           `-- tough-cookie@2.2.2
```

**Comment by franck34** [comment]
@evilpacket @lukekarrys @nlf @wraithgar

Please, could you update package dependencies ?

Thank you

**Comment by abenhamdine** [comment]
This gonna break some builds now (mine is), because nsp 2.X relies on joi, which depends on moment 2.19.2 which has a vulnerability detected by nsp since today 😞 
The vulnerability disappears with nsp 3.x, because the joi dependency is no longer there.

So please update to nsp 3.x

Thx.

**Comment by nathany** [comment]
gulp-nsp depends on an old version of nsp, which depends on an unpatched version of hoek with this vulnerability: https://nodesecurity.io/advisories/566 
https://hackerone.com/reports/310439

<img width="666" alt="hoek" src="https://user-images.githubusercontent.com/4566/36272559-222d5232-123f-11e8-8dae-65a209378538.png">

nsp 3.x depends on hoek 4.2, and 4.2.1 has a backported patch
