### ISSUE TITLE
gulp-nsp 3.0 ignoring exceptions

### ISSUE THREAD

**Issue by nathany** [nodesecurity/gulp-nsp#43]
@nlf Thanks for releasing 3.0  to resolve this issue: https://github.com/nodesecurity/gulp-nsp/issues/39#issuecomment-366010196. 

Unfortunately I'm running into some issues after upgrading our project to 3.0.

I'm now seeing `gulp nsp` output vulnerability warnings that are in the exceptions list.

.nsprc
```json
{
  "exceptions": [
    "https://nodesecurity.io/advisories/534",
    "https://nodesecurity.io/advisories/566"
  ]
}
```

```
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Regular Expression Denial of Service                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ debug                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 3.7 (Low)                                                          │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 0.7.4                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <= 2.6.8 || >= 3.0.0 <= 3.0.1                                      │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ my-project@0.0.1 > tcp-port-used@0.1.2 > debug@0.7.4               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/534                             │
└────────────┴────────────────────────────────────────────────────────────────────┘
```

This issue: https://github.com/stdarg/tcp-port-used/pull/5

I'm also not seeing the other 566 vulnerability if I remove the .nsprc file.  https://github.com/mapbox/node-pre-gyp/issues/346

If I downgrade gulp-nsp, I see both vulnerabilities when there is no .nsprc file, and they both can be ignored with the .nsprc.

This is the output from gulp-nsp 2.x:

```
 hoek    2.16.3      > 4.2.0 < 5.0.0 || >= 5.0.3    my-project@0.0.1 > gulp@4.0.0 > glob-watcher@5.0.1 > chokidar@2.0.2 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > hawk@3.1.3 > hoek@2.16.3   https://nodesecurity.io/advisories/566 
 debug   0.7.4       >= 2.6.9 < 3.0.0 || >= 3.1.0   my-project@0.0.1 > tcp-port-used@0.1.2 > debug@0.7.4                                                                                    https://nodesecurity.io/advisories/534 
```

Also noticed a Drone test failure on your repo.

**Comment by nlf** [comment]
i just published gulp-nsp@3.0.1, give that a spin and let me know if it fixes your issue

**Comment by nathany** [comment]
That solves the issue with the exception not working. Thanks!

However,  it's no longer reporting  https://nodesecurity.io/advisories/566 for node-pre-gyp.

<img width="589" alt="hoek2" src="https://user-images.githubusercontent.com/4566/36282573-d0f0f106-125e-11e8-8640-0e7d1b31e90a.png">

```
├─┬ babel-cli@6.26.0
│ └─┬ chokidar@1.7.0
│   └─┬ fsevents@1.1.3
│     └─┬ node-pre-gyp@0.6.39
│       └─┬ hawk@3.1.3
│         ├─┬ boom@2.10.1
│         │ └── hoek@2.16.3  deduped
│         ├── hoek@2.16.3 
│         └─┬ sntp@1.0.9
│           └── hoek@2.16.3  deduped
```

```
[14:45:26] Starting 'security'...
[14:45:34] (+) No known vulnerabilities found
[14:45:34] Finished 'security' after 8.33 s
```

.nsprc
```
{
  "exceptions": [
    "https://nodesecurity.io/advisories/534"
  ]
}
```

**Comment by nlf** [comment]
that would be because `chokidar`, the package that ultimately brings in node-pre-gyp is an optional dependency of babel-cli (the top level package you're testing), and currently optional deps are skipped

**Comment by nathany** [comment]
Okay. At least it's intentional then. But did that behaviour change between nsp 2.7 and nsp 3.2.1? 

The output from gulp-nsp 2.x (no .nsprc):

```
 hoek    2.16.3      > 4.2.0 < 5.0.0 || >= 5.0.3    my-project@0.0.1 > gulp@4.0.0 > glob-watcher@5.0.1 > chokidar@2.0.2 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > hawk@3.1.3 > hoek@2.16.3   https://nodesecurity.io/advisories/566 
 debug   0.7.4       >= 2.6.9 < 3.0.0 || >= 3.1.0   my-project@0.0.1 > tcp-port-used@0.1.2 > debug@0.7.4                                                                                    https://nodesecurity.io/advisories/534 
```

**Comment by nlf** [comment]
shouldn't have.. nothing in the nsp client, or gulp-nsp does anything with optionalDependencies at all and never has.

the output you're showing from gulp-nsp 2.x looks to be from a different project, as it shows a dependency on gulp@4.0.0 bringing in glob-watcher@5.0.1 (a direct dependency, not optional) which in turn brings in the version of chokidar with the vulnerable package.

the output you showed from gulp-nsp 3.x showed a dependency tree from babel-cli, which is entirely different due to chokidar being an optional dependency.

**Comment by nathany** [comment]
Thanks for clarifying that for me. And also thank you for responding quickly and upgrading gulp-nsp.

Cheers

**Comment by nlf** [comment]
happy to help, good catch on the exceptions not working and thank you for reporting it so quickly!
